services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    entrypoint: ["/usr/bin/bash", "/root/models.sh"]
    tty: true
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models.sh:/root/models.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Give time for models to download before healthcheck starts failing if server is up
    networks:
      - ollama
  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ollama-web
    depends_on:
      backend:
        condition: service_started
    ports:
      - 3000:3000
    # volumes:
    #   - ./web:/web
    restart: unless-stopped
    networks:
      - ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ollama-backend
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - ollama-backend-db:/backend/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    networks:
      - ollama

volumes:
  ollama:
  ollama-backend-db: {}

networks:
  ollama:
    driver: bridge